name: Blog Posts

on:
  schedule: [{ cron: "0 2 * * *" }] # every day at 2am
  workflow_dispatch: # manually run workflow
permissions:
  contents: write # write the generated contents to the readme

jobs:
  blog-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull tifan.me posts
        uses: gautamkrishnar/blog-post-workflow@1.8.4
        with:
          feed_list: "https://tifan.me/feed.xml"
          template: "$newline- $date [$title]($url)$newline"
          date_format: "mmm d, yyyy"
