name: Blog post
on:
  schedule: [{ cron: "0 * * * *" }] # Runs every hour, on the hour
  push: { branches: ["master", "main"] } # Run workflow when pushing on master/main
  workflow_dispatch: # Run workflow manually
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  blog-post:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull tifan.me posts
        uses: gautamkrishnar/blog-post-workflow@1.8.4
        with:
          feed_list: "https://tifan.me/feed.xml"
