name: Waka Readme
on:
  schedule: [{ cron: "0 * * * *" }] # Runs every hour, on the hour
  push: { branches: ["master", "main"] } # Run workflow when pushing on master/main
  workflow_dispatch: # Run workflow manually

jobs:
  waka-readme:
    name: Update this repo's README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
